notepad/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from stickynote.sitemaps import StaticViewSitemap

sitemaps = {
    'static': StaticViewSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('stickynote.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
    path('robots.txt', include('robots.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('captcha/', include('captcha.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stickynote/urls.py
from django.urls import path
from .views import *

app_name = 'notepad'

urlpatterns = [
    path('',index_view,name='home'),
    path('save/',form_view,name='forms')
]

stickynote/models.py
from django.db import models

class notes(models.Model):
    title=models.CharField(max_length=255)
    text=models.TextField()

    def __str__(self):
        return self.title

stickynote/forms.py
from django import forms
from .models import notes

class NotesForm(forms.ModelForm):
    class Meta:
        model=notes
        fields='__all__'        

stickynote/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from .models import *
from .forms import NotesForm

def index_view(request):
    note=notes.objects.all()
    context={'note':note}
    return render(request,'sticky_them.html',context)

def form_view(request):
    if request.method=='POST':
        note=NotesForm(request.POST)
        if note.is_valid():
            note.save()
            return HttpResponseRedirect('/')
    form=NotesForm()
    return render(request,'save.html',{'form':form})

templates/save.html
<!DOCTYPE html>
<html>
  <head>
    <title>Contact us</title>
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700" rel="stylesheet">
    <style>
      * {
      box-sizing: border-box;
      }
      html, body {
      min-height: 100vh;
      padding: 0;
      margin: 0;
      font-family: Roboto, Arial, sans-serif;
      font-size: 14px; 
      color: #666;
      }
      input, textarea { 
      outline: none;
      }
      body {
      display: flex;
      justify-content: center;
      align-items: center;
      padding: 20px;
      background: #5a7233;
      }
      h1 {
      margin-top: 0;
      font-weight: 500;
      }
      form {
      position: relative;
      width: 80%;
      border-radius: 30px;
      background: #fff;
      }
      .form-left-decoration,
      .form-right-decoration {
      content: "";
      position: absolute;
      width: 50px;
      height: 20px;
      border-radius: 20px;
      background: #5a7233;
      }
      .form-left-decoration {
      bottom: 60px;
      left: -30px;
      }
      .form-right-decoration {
      top: 60px;
      right: -30px;
      }
      .form-left-decoration:before,
      .form-left-decoration:after,
      .form-right-decoration:before,
      .form-right-decoration:after {
      content: "";
      position: absolute;
      width: 50px;
      height: 20px;
      border-radius: 30px;
      background: #fff;
      }
      .form-left-decoration:before {
      top: -20px;
      }
      .form-left-decoration:after {
      top: 20px;
      left: 10px;
      }
      .form-right-decoration:before {
      top: -20px;
      right: 0;
      }
      .form-right-decoration:after {
      top: 20px;
      right: 10px;
      }
      .circle {
      position: absolute;
      bottom: 80px;
      left: -55px;
      width: 20px;
      height: 20px;
      border-radius: 50%;
      background: #fff;
      }
      .form-inner {
      padding: 40px;
      }
      .form-inner input,
      .form-inner textarea {
      display: block;
      width: 100%;
      padding: 15px;
      margin-bottom: 10px;
      border: none;
      border-radius: 20px;
      background: #d0dfe8;
      }
      .form-inner textarea {
      resize: none;
      }
      button {
      width: 100%;
      padding: 10px;
      margin-top: 20px;
      border-radius: 20px;
      border: none;
      border-bottom: 4px solid #3e4f24;
      background: #5a7233; 
      font-size: 16px;
      font-weight: 400;
      color: #fff;
      }
      button:hover {
      background: #3e4f24;
      } 
      @media (min-width: 568px) {
      form {
      width: 60%;
      }
      }
    </style>
  </head>
  <body>

    <form action="{% url 'notepad:forms' %}" class="decor" method="post">{% csrf_token %}
      <div class="form-left-decoration"></div>
      <div class="form-right-decoration"></div>
      <div class="circle"></div>
      <div class="form-inner">
        <h1>Imagin...</h1>
        <input type="text" placeholder="Title" name="title">
        <textarea placeholder="Text..." rows="5" name="text"></textarea>
        <button type="submit">Submit</button>
      </div>
    </form>
  </body>
</html>

templates/sticky_them.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>littel dream</title>
    <style>
        body{
            background-color: #5A7233;
            text-align: center;
            font-family: sans-serif;
            margin: 0;
        }
        .container{
            background-color: whitesmoke;
            width: 1000px;
            height: auto;
            margin: auto;
            margin-top: 40px;
            border-radius: 15px;
        }
        .box{
            background-color: #9bc162;
            margin: 5px 5px;
            padding: 1px;
            border: 2px solid whitesmoke;
            border-radius: 15px;
        }
        .title{
            background-color:whitesmoke;
            margin: 0 30px;
            border-radius: 20px;
        }
        .link_box{
            margin: auto;
            background-color: white;
            width: 320px;
            height: 40px;
            border-radius:0 0px 20px 20px;
            
        }
        .link{
            text-decoration: none;
            padding: 20px;
            padding-left: 126px;
            padding-right: 126px;
            padding-bottom: 6px;
            color: #666;
            font-size: 30px;
        }
    </style>
</head>
<body>
    <div class="link_box">
        <a class="link" href="{% url 'notepad:forms' %}">Save</a>
    </div>
    
<div class="container">
    {% for n in note %}
    <div class="box">
        <div class="title">
            <h2>{{n.title}}</h2>
        </div>
        <p>{{n.text|safe}}</p>
    </div>
    {% endfor %}
</div>
</body>
</html>